/**
 * Document Config Loader
 * 
 * Loads document-level configuration from config.json files sibling to spec entries.
 * Provides fallback ID generation when config is not present.
 */

import type { FileProvider } from '#src/file-provider/types';
import { isFileNotFoundError } from '#src/file-provider/types';
import type { DocumentConfig, ResolvedDocumentConfig } from './types.js';
import { interpolateEnvVars } from './env.js';


/**
 * Generate an auto ID from entry path
 * 
 * Pattern: <parent-folder-name>-<file-name> (without extension)
 * Example: /spec/workspace/pkg-a/index.html → pkg-a-index
 */
export function generateIdFromPath(entryPath: string): string {
    // Normalize path separators
    const normalizedPath = entryPath.replace(/\\/g, '/');
    const parts = normalizedPath.split('/').filter(p => p.length > 0);

    if (parts.length === 0) {
        return 'unknown';
    }

    // Get filename without extension
    const filename = parts[parts.length - 1];
    const filenameWithoutExt = filename.replace(/\.[^.]+$/, '');

    // Get parent folder name (if exists)
    if (parts.length >= 2) {
        const parentFolder = parts[parts.length - 2];
        return `${parentFolder}`;
    }

    return filenameWithoutExt;
}

/**
 * Get the config.json path sibling to an entry file
 */
export function getConfigPath(entryPath: string): string {
    // Replace the filename with config.json
    const normalizedPath = entryPath.replace(/\\/g, '/');
    const lastSlash = normalizedPath.lastIndexOf('/');

    if (lastSlash === -1) {
        return 'config.json';
    }

    return normalizedPath.substring(0, lastSlash + 1) + 'config.json';
}

/**
 * Load document configuration from config.json sibling to entry
 * 
 * If config.json doesn't exist, returns a resolved config with auto-generated ID.
 * If configPath is provided, that file is used instead of sibling discovery.
 * 
 * @param fileProvider - File provider to read from
 * @param entryPath - Path to the spec entry file (e.g., index.html)
 * @param env - Optional environment object for variable interpolation
 * @param configPath - Optional explicit path to the config file
 * @returns Resolved config with ID and dependencies
 */
export async function loadDocConfig(
    fileProvider: FileProvider,
    entryPath: string,
    env?: Record<string, string | undefined>,
    configPath?: string
): Promise<ResolvedDocumentConfig> {
    const resolvedConfigPath = configPath ?? getConfigPath(entryPath);
    const canonicalPath = fileProvider.canonicalize(resolvedConfigPath);
    const diagnostics: string[] = [];

    let content: string;
    try {
        content = await fileProvider.readText(canonicalPath);
    } catch (error) {
        if (isFileNotFoundError(error)) {
            // Config doesn't exist - auto-generate ID
            return {
                id: generateIdFromPath(entryPath),
                deps: [],
                autoGenerated: true,
            };
        }

        diagnostics.push(
            `Failed to read config "${canonicalPath}": ${error instanceof Error ? error.message : String(error)}. Falling back to auto-generated config.`
        );
        return {
            id: generateIdFromPath(entryPath),
            deps: [],
            autoGenerated: true,
            diagnostics,
        };
    }

    let config: DocumentConfig;
    try {
        const interpolatedContent = interpolateEnvVars(content, env);
        config = JSON.parse(interpolatedContent) as DocumentConfig;
    } catch (error) {
        diagnostics.push(
            `Invalid JSON in config "${canonicalPath}": ${error instanceof Error ? error.message : String(error)}. Falling back to auto-generated config.`
        );
        return {
            id: generateIdFromPath(entryPath),
            deps: [],
            autoGenerated: true,
            diagnostics,
        };
    }

    // Determine ID (use provided or auto-generate)
    const hasValidId = config.id && typeof config.id === 'string' && config.id.trim().length > 0;
    const id = hasValidId ? config.id as string : generateIdFromPath(entryPath);
    if (!hasValidId) {
        diagnostics.push(`Config "${canonicalPath}" is missing a valid "id"; generated "${id}" from entry path.`);
    }

    const deps = Array.isArray(config.deps) ? config.deps : [];
    if (config.deps !== undefined && !Array.isArray(config.deps)) {
        diagnostics.push(`Config "${canonicalPath}" has non-array "deps"; using an empty dependency list.`);
    }

    return {
        ...config,
        id,
        deps,
        autoGenerated: !hasValidId,
        diagnostics: diagnostics.length > 0 ? diagnostics : undefined,
    };
}
