import { describe, expect, it } from 'vitest';
import { MemoryFileProvider } from '#src/file-provider/memory';
import { loadDocConfig } from '../doc-config.js';
import { normalizeConfig } from '../normalize.js';
import { preprocess } from '#src/preprocess/pipeline';

describe('loadDocConfig diagnostics', () => {
    it('returns diagnostics and auto-generated config when JSON is invalid', async () => {
        const fileProvider = new MemoryFileProvider({
            '/spec/config.json': '{ invalid json',
        });

        const result = await loadDocConfig(fileProvider, '/spec/index.md');

        expect(result.autoGenerated).toBe(true);
        expect(result.id).toBe('spec');
        expect(result.diagnostics?.length).toBeGreaterThan(0);
        expect(result.diagnostics?.[0]).toContain('Invalid JSON');
    });
});

describe('specProfile passthrough', () => {
    it('normalizes root specProfile into SpecConfig', () => {
        const normalized = normalizeConfig({
            id: 'doc',
            deps: [],
            specProfile: 'w3c',
            autoGenerated: false,
        });

        expect(normalized.specProfile).toBe('w3c');
    });

    it('propagates non-fatal config diagnostics through preprocess results', async () => {
        const fileProvider = new MemoryFileProvider({
            '/spec/index.md': '# Title',
            '/spec/config.json': '{ invalid json',
        });

        const result = await preprocess({
            entry: '/spec/index.md',
            fileProvider,
        });

        expect(result.config.id).toBe('spec');
        expect(result.diagnostics?.length).toBeGreaterThan(0);
        expect(result.diagnostics?.[0]).toContain('Invalid JSON');
    });
});
