import { describe, it, expect, vi, afterEach } from 'vitest';
import { MemoryFileProvider } from '#src/file-provider/memory';
import { preprocess } from '#src/preprocess/pipeline';
import { normalizeConfig } from '../normalize.js';
import type { ResolvedDocumentConfig, DocumentConfig } from '../types.js';

/**
 * Helper to create a ResolvedDocumentConfig for testing normalizeConfig
 */
function createResolvedConfig(partial: DocumentConfig): ResolvedDocumentConfig {
    return {
        id: 'test-doc',
        deps: [],
        autoGenerated: true,
        ...partial,
    };
}

afterEach(() => {
    vi.useRealTimers();
});

describe('Config Priority Rules', () => {
    describe('lastUpdateDate priority', () => {
        it('uses root-level lastUpdateDate when both are present', () => {
            const docConfig: DocumentConfig = {
                title: 'Test Spec',
                lastUpdateDate: '2026-01-11', // Root priority
                respec: {
                    modificationDate: '2026-01-10', // ReSpec fallback
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.lastUpdateDate).toBe('2026-01-11');
        });

        it('falls back to respec.modificationDate when root is missing', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'Test Spec',
                    modificationDate: '2026-01-10',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.lastUpdateDate).toBe('2026-01-10');
        });

        it('is undefined if neither are present', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'Test Spec',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.lastUpdateDate).toBeUndefined();
        });

        it('resolves [DATE] placeholder on root-level lastUpdateDate', () => {
            vi.useFakeTimers();
            vi.setSystemTime(new Date('2026-03-03T12:00:00Z'));

            const docConfig: DocumentConfig = {
                lastUpdateDate: '[DATE]',
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.lastUpdateDate).toBe('2026-03-03');
        });

        it('resolves [DATE] placeholder from respec.modificationDate when root is missing', () => {
            vi.useFakeTimers();
            vi.setSystemTime(new Date('2026-03-03T12:00:00Z'));

            const docConfig: DocumentConfig = {
                respec: {
                    modificationDate: '[DATE]',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.lastUpdateDate).toBe('2026-03-03');
        });
    });

    describe('ReSpec field mapping', () => {
        it('correctly maps various ReSpec fields to normalized config', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'Test Spec',
                    shortName: 'test',
                    specStatus: 'ED',
                    publishDate: '2026-01-01',
                    abstract: 'Abstract content',
                    noTOC: true,
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.title).toBe('Test Spec');
            expect(config.shortName).toBe('test');
            expect(config.status).toBe('ED');
            expect(config.publishDate).toBe('2026-01-01');
            expect(config.abstract).toBe('Abstract content');
            expect(config.tocEnabled).toBe(false);
        });
    });

    describe('Pipeline Integration', () => {
        it('prioritizes root lastUpdateDate in the full preprocess pipeline', async () => {
            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    lastUpdateDate: '2026-01-11', // Root
                    respec: {
                        modificationDate: '2026-01-10', // Fallback
                    },
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/spec/config.json',
                fileProvider: fp,
            });

            expect(result.config.lastUpdateDate).toBe('2026-01-11');
        });

        it('falls back to respec.modificationDate in the full preprocess pipeline', async () => {
             const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    respec: {
                        modificationDate: '2026-01-10',
                    },
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/spec/config.json',
                fileProvider: fp,
            });

            expect(result.config.lastUpdateDate).toBe('2026-01-10');
        });

        it('resolves [DATE] placeholder in the full preprocess pipeline', async () => {
            vi.useFakeTimers();
            vi.setSystemTime(new Date('2026-03-03T12:00:00Z'));

            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    respec: {
                        modificationDate: '[DATE]',
                    },
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/spec/config.json',
                fileProvider: fp,
            });

            expect(result.config.lastUpdateDate).toBe('2026-03-03');
        });

        it('uses explicit configPath instead of sibling config', async () => {
            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    id: 'sibling-id',
                    title: 'Sibling Title',
                }),
                '/shared/custom-config.json': JSON.stringify({
                    id: 'custom-id',
                    title: 'Custom Title',
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/shared/custom-config.json',
                fileProvider: fp,
            });

            expect(result.config.id).toBe('custom-id');
            expect(result.config.title).toBe('Custom Title');
        });
    });

    describe('maturityLevel priority', () => {
        it('uses root-level maturityLevel when both are present', () => {
            const docConfig: DocumentConfig = {
                maturityLevel: 'stable', // Root priority
                respec: {
                    title: 'Test Spec',
                    specStatus: 'ED', // ReSpec fallback maps to 'draft'
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.maturityLevel).toBe('stable');
            expect(config.status).toBe('ED'); // status is still preserved
        });

        it('falls back to mapped respec.specStatus when root is missing', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'Test Spec',
                    specStatus: 'CR', // Maps to 'prerelease'
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.maturityLevel).toBe('prerelease');
            expect(config.status).toBe('CR');
        });

        it('maps common specStatus values correctly', () => {
            const mappings: Array<[string, string]> = [
                ['ED', 'draft'],
                ['WD', 'draft'],
                ['CR', 'prerelease'],
                ['REC', 'stable'],
                ['unofficial', 'incubating'],
            ];

            for (const [specStatus, expected] of mappings) {
                const docConfig: DocumentConfig = { respec: { specStatus } };
                const config = normalizeConfig(createResolvedConfig(docConfig));
                expect(config.maturityLevel).toBe(expected);
            }
        });

        it('is undefined if neither are present', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'Test Spec',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.maturityLevel).toBeUndefined();
        });

        it('prioritizes root maturityLevel in the full preprocess pipeline', async () => {
            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    maturityLevel: 'stable', // Root
                    respec: {
                        specStatus: 'ED', // Fallback would map to 'draft'
                    },
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/spec/config.json',
                fileProvider: fp,
            });

            expect(result.config.maturityLevel).toBe('stable');
        });

        it('falls back to mapped respec.specStatus in the full preprocess pipeline', async () => {
            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    respec: {
                        specStatus: 'REC',
                    },
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                configPath: '/spec/config.json',
                fileProvider: fp,
            });

            expect(result.config.maturityLevel).toBe('stable');
        });
    });

    describe('title priority', () => {
        it('uses root-level title when both are present', () => {
            const docConfig: DocumentConfig = {
                title: 'Root Title', // Root priority
                respec: {
                    title: 'ReSpec Title', // Fallback
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.title).toBe('Root Title');
        });

        it('falls back to respec.title when root is missing', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    title: 'ReSpec Title',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.title).toBe('ReSpec Title');
        });
    });

    describe('repository priority', () => {
        it('uses root-level repository when both root and respec are present', () => {
            const docConfig: DocumentConfig = {
                repository: 'https://github.com/root/priority-repo',
                respec: {
                    repository: 'https://github.com/respec/fallback-repo',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));
            expect(config.repository).toBe('https://github.com/root/priority-repo');
        });

        it('falls back to respec.repository when root-level repository is missing', () => {
            const docConfig: DocumentConfig = {
                respec: {
                    repository: 'https://github.com/respec/fallback-repo',
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));
            expect(config.repository).toBe('https://github.com/respec/fallback-repo');
        });
    });

    describe('custom overrides', () => {
        it('passes through custom properties', () => {
            const docConfig: DocumentConfig = {
                custom: {
                    myCustomField: 'value',
                    analytics: { enabled: true },
                },
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));

            expect(config.custom).toEqual({
                myCustomField: 'value',
                analytics: { enabled: true },
            });
        });
    });

    describe('specProfile passthrough', () => {
        it('keeps root-level specProfile in normalized config', () => {
            const docConfig: DocumentConfig = {
                specProfile: 'w3c',
            };

            const config = normalizeConfig(createResolvedConfig(docConfig));
            expect(config.specProfile).toBe('w3c');
        });

        it('keeps specProfile in preprocess output', async () => {
            const fp = new MemoryFileProvider({
                '/spec/index.md': '# Title',
                '/spec/config.json': JSON.stringify({
                    id: 'spec-a',
                    specProfile: 'w3c',
                }),
            });

            const result = await preprocess({
                entry: '/spec/index.md',
                fileProvider: fp,
            });

            expect(result.config.specProfile).toBe('w3c');
        });
    });
});
